// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://db.techpinoy.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16amNtdGx0d2RjcGJkdnVubXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDM0MDAsImV4cCI6MjA2NDE3OTQwMH0.yap8eSNbFjYJsz43kwUZtGh8O3V7V9YPQC5bgx3cFWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});